### PR TITLE
Updated documentation for 2.9.0

### LINKED ISSUE #21: update /content/riak/kv/2.2.6/configuring/ to v 2.9.X/3.0
Update contained pages & sub categories /v3-multi-datacenter/ & /v2-multi-datacenter/ to V2.9.X

### LINKED ISSUE #32: Update /content/riak/kv/2.2.6/setup/planning/backend/ pages to v2.9.x
Update /content/riak/kv/2.2.6/setup/planning/backend/  pages to reflect changes for v2.9.x

### PR DESCRIPTION
**Pull request by JMercerGit**
Updated documentation in backend.md to include information on the new leveled backend added in 2.9.0
Updated references to docs.basho.com to tiot.jp links
Added a new leveled backend page to /setup/planning/backend/

This closes #32 and closes #21

### CODE REVIEW

**Review by Bob-The-Marauder — COMMENTED** [review]
I'm generally happy with that. I did notice a lack of Leveled weaknesses. I can think of two off the top of my head:
1. Leveled is still a comparatively new technology and more likely to suffer from edge case issues than Bitcask or LevelDB simply because they've been around longer and have been more thoroughly tested via usage in customer environments.
2. Leveled works better with medium to larger sized objects. It works perfectly well with small objects but the additional diskspace overhead may render LevelDB a better choice if disk space is at a premium and all of your data will be exclusively limited a few KB or less. This may change as Leveled matures though.

**Comment by JMercerGit** [comment]
> I'm generally happy with that. I did notice a lack of Leveled weaknesses. I can think of two off the top of my head:
> 
> 1. Leveled is still a comparatively new technology and more likely to suffer from edge case issues than Bitcask or LevelDB simply because they've been around longer and have been more thoroughly tested via usage in customer environments.
> 2. Leveled works better with medium to larger sized objects. It works perfectly well with small objects but the additional diskspace overhead may render LevelDB a better choice if disk space is at a premium and all of your data will be exclusively limited a few KB or less. This may change as Leveled matures though.

Thanks, I've included those in the new commit.

**Comment by JMercerGit** [comment]
Added an extra commit that fixes some outdated links

**Comment by JMercerGit** [comment]
Additional commits close #44 and #41

**Comment by JMercerGit** [comment]
Additional commit closes #34

**Comment by JMercerGit** [comment]
This request also closes  #37

**Review by pjaclark — APPROVED** [review]

**Comment by JMercerGit** [comment]
Also closes #14

**Review by daniel020403 — APPROVED** [review]

**Review by Bob-The-Marauder — CHANGES_REQUESTED** [review]
content/riak/kv/2.9.0/configuring/reference.md
`[config backend leveled]: ../../setup/planning/backend/bitcask/#configuring-leveled` looks like a path typo - leveled config inside bitcask config?

content/riak/kv/2.9.0/developing/app-guide.md
`out [Riak CS](https://docs.riak.com/riakcs/latest/) instead, as Riak` should really point to our docs

content/riak/kv/2.9.0/developing/app-guide/replication-properties.md
```
2 of 3 vnodes agree on the value, and those 2 are the first to reach the coordinating node | The value is returned to the client. Read repair will deal with the conflict per the later scenarios, which means that a future read may return a different value or <a href="https://www.tiot.jp/riak-docs/riak/kv/2.2.6/learn/concepts/causal-context/#siblings">siblings</a>
2 conflicting values reach the coordinating node and <a href="https://www.tiot.jp/riak-docs/riak/kv/2.2.6/learn/concepts/causal-context/#vector-clocks">vector clocks</a> allow for resolution | The vector clocks are used to resolve the conflict and return a single value, which is propagated via read repair to the relevant vnodes
```
why are we reverting back to 2.2.6 links from the 2.9.0 links originally there?

**Review by Bob-The-Marauder — APPROVED** [review]
That covers my concerns. We may have missed something else somewhere but for the moment, let's proceed.

**Pull request merged**
