### PR TITLE
Updated bucket and key for the Java and Ruby examples for consistency.

### PR DESCRIPTION
**Pull request by daniel020403**

### CODE REVIEW

**Review by JMercerGit — APPROVED** [review]

**Review by Bob-The-Marauder — COMMENTED** [review]
Despite the fact that my Ruby abilities are probably less than a 1st year CSE student, I still feel that  lines 177-179 are still talking about sets rather than gsets.

**Comment by daniel020403** [comment]
> Despite the fact that my Ruby abilities are probably less than a 1st year CSE student, I still feel that lines 177-179 are still talking about sets rather than gsets.

@Bob-The-Marauder, I just updated the bucket and key names in the ruby example to make them consistent with the rest. Changing the other parts of that code would still need some tests. There is the possibility that changes on the client might be needed.

**Comment by Bob-The-Marauder** [comment]
Probably a test for all of the gsets examples is not a bad idea. As behaviour for some clients is essentially identical to sets other than being called gsets, it is possible that Ruby could be one of those but testing would guarantee it. I'd say get this as logically close as possible to what it should be for Ruby, commit and then look at test going from there.

**Comment by pjaclark** [comment]
@daniel020403 Update for Ruby and then re-do a review.

**Pull request merged**
