### PR TITLE
Version History updates for V2.0.0 - V2.9.10

### PR DESCRIPTION
**Pull request by JMercerGit**
Version History updates for V2.0.0 - V2.9.10

### CODE REVIEW

**Comment by pjaclark** [comment]
Why are there updates to 3.0.6, 3.0.7 and 3.2.0? Search was removed from there. Should those files be deleted?

**Comment by JMercerGit** [comment]
> Why are there updates to 3.0.6, 3.0.7 and 3.2.0? Search was removed from there. Should those files be deleted?

They should have been.. I guess I can remove those too. Checking

**Comment by JMercerGit** [comment]
Fixed @pjaclark

**Comment by pjaclark** [comment]
LGTM
+1

**Review by pjaclark — APPROVED** [review]
LGTM

**Pull request merged**
